### ISSUE TITLE
Text isn't displaying on top of the background image

### ISSUE THREAD

**Issue by mrod23** [driftyco/ionic-preview-app#26] opened 2016-05-09 11:25 UTC
The text isn't displaying on top of the background image. The text is displaying under the background image. 

This is in reference to the background card sass and html files.

**Comment by brandyscarney** [comment] 2016-05-17 14:20
Hey, I'm not seeing this. Are you using the latest code from the preview app and can you give me some more details if you're still having this issue? Are you running the preview app locally or viewing it in the docs?

![screen shot 2016-05-17 at 10 19 21 am](https://cloud.githubusercontent.com/assets/6577830/15325626/060ffb36-1c19-11e6-823f-3cb9b9b330a5.png)

**Comment by mrod23** [comment] 2016-05-19 00:15
Hi, 

I added the code to my own app. Here's what I added.
The text is appearing below the picture. Not on top of it. Not sure what I'm doing wrong. 

Appreciate your help. 

main.css
.card-background-page {

  ion-card {
    position: relative;
    text-align: center;
  }

  .card-title {
    position: absolute;
    top: 36%;
    font-size: 2.0em;
    width: 100%;
    font-weight: bold;
    color: #fff;
  }

  .card-subtitle {
    font-size: 1.0em;
    position: absolute;
    top: 52%;
    width: 100%;
    color: #fff;
  }
}

html
<ion-content class="card-background-page" >      
        <ion-card >
            <img src="../../img/wolves.png"/>
            <div class="card-title">Madison</div>
            <div class="card-subtitle">28 Listings</div>
        </ion-card>
</ion-content>

**Comment by brandyscarney** [comment] 2016-05-19 17:23
Do you have any other styles overriding it? I added it to the account page in the [conference app](https://github.com/driftyco/ionic-conference-app). In `account.html`:

```

<ion-navbar *navbar>
  <button menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>
  <ion-title>Account</ion-title>
</ion-navbar>

<ion-content class="outer-content">
  <ion-card>
    <img src="https://assets.hipmunk.com/assets/dest_head/4da3309a2a0ceb6e950109f6"/>
    <div class="card-title">Madison</div>
    <div class="card-subtitle">28 Listings</div>
  </ion-card>

  ...
</ion-content>
```

and in the `account.scss` file:

```
.account-page {

  ion-card {
    position: relative;
    text-align: center;
  }

  .card-title {
    position: absolute;
    top: 36%;
    font-size: 2.0em;
    width: 100%;
    font-weight: bold;
    color: #fff;
  }

  .card-subtitle {
    font-size: 1.0em;
    position: absolute;
    top: 52%;
    width: 100%;
    color: #fff;
  }
}
```

and I am seeing the text on top:

![screen shot 2016-05-19 at 1 21 41 pm](https://cloud.githubusercontent.com/assets/6577830/15402956/a9513a6a-1dc4-11e6-97d9-c9620fff51b0.png)

There are a number of things that could be causing it, but there might be some css messing with it.

**Comment by akaushik79** [comment] 2016-05-27 08:44
I am facing similar issue. Text is appearing at bottom of the image rather than on top of background image.

I created a fresh page and copy pasted the code given above to test it but still same issue.

**Comment by brandyscarney** [comment] 2016-06-02 00:56
I'm sorry but I can't reproduce this issue. I have generated a new page and pasted the same as above and each time I see the text on top:

![screen shot 2016-06-01 at 8 56 40 pm](https://cloud.githubusercontent.com/assets/6577830/15730506/583f0b26-283b-11e6-8e56-a5922c436555.png)

If you could create a github repo or plunker that shows the problem that would be helpful, thank you!

**Comment by mrod23** [comment] 2016-06-05 22:18
I got it to work for me using the below code. Moved around the CSS a little bit

`<ion-card class="card card-background-page" ui-sref="app.ventureDetails({id: venture._id})">
                <img src="../../img/wolves.png">
                <div class="card-title">{{venture.name}}</div>
                <div class="card-price">$75</div>
                <div class="card-avatar">
                    <img class="card-avatar" src="../../img/daenerys.png">
                </div>    
            </ion-card> `


`.card-background-page {
    position: relative;
    text-align: center;
    background-blend-mode: multiply;

  }

.card-image-blend {
  opacity: 80%;
}

  .card-title {
    position: absolute;
    top: 69%;
    font-size: 2.0em;
    width: 100%;
    text-align: left;
    color: #fff;
  }

  .card-title-home {
    position: absolute;
    top: 69%;
    font-size: 2.0em;
    width: 100%;
    text-align: center;
    color: #fff;
  }`

**Comment by brandyscarney** [comment] 2016-06-21 15:08
I'm going to close this since you got this working. Thanks!

**Closed by brandyscarney** 2016-06-21 15:08 UTC
