### ISSUE TITLE
Every time i try this code i get ERROR and wont open Modal at all

### ISSUE THREAD

**Issue by jackloverde** [driftyco/ionic-preview-app#74] opened 2016-12-18 22:28 UTC
Every time i get this error:
`ModalCmp ionViewPreLoad error: No component factory found for "nameOfTheClass"`.
I create a blank project, insert a button on home to open the modal ( exactly the same ) and get this error.

-----------
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.1 Build version 8B62
-----------

How to open ?

**Comment by danielAlbuquerque** [comment] 2016-12-25 22:45
@jackloverde , in your app.module.ts import "nameOfTheClass", include them on declarations and entryComponents inside @NgModule and use "export class nameOfTheClass" in your class. Works for me

**Comment by brandyscarney** [comment] 2017-01-03 15:50
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!

**Closed by brandyscarney** 2017-01-03 15:50 UTC
