### ISSUE TITLE
Blank screen in android device

### ISSUE THREAD

**Issue by ehussain** [driftyco/ionic-preview-app#34] opened 2016-06-11 07:04 UTC
I have pulled this repository and tried to run in browser using `ionic serve` and it worked perfectly well.
However when I tried to run this in android device using `ionic run android` I get blank screen on device. 

I tried to read the device logs using android monitor and found following error.

```
06-11 12:30:59.526 10525-10525/io.ionic.starter I/chromium: [INFO:CONSOLE(32395)] "Uncaught TypeError: undefined is not a function", source: file:///android_asset/www/build/js/app.bundle.js (32395)
```

Here is complete stack trace

```
06-11 12:29:59.941 620-620/? W/PackageManager: Failure retrieving resources for io.ionic.starter: Resource ID #0x0
06-11 12:30:00.080 8393-8393/io.ionic.starter W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
06-11 12:30:00.980 620-620/? W/PackageManager: Failure retrieving resources for io.ionic.starter: Resource ID #0x0
06-11 12:30:01.826 467-2132/? I/ActivityManager: Killing 8393:io.ionic.starter/u0a217 (adj 9): remove task
06-11 12:30:01.845 467-483/? I/WindowState: WIN DEATH: Window{eae97b9 u0 io.ionic.starter/io.ionic.starter.MainActivity}
06-11 12:30:49.900 467-498/? D/PackageManager: Renaming /data/app/vmdl1438886297.tmp to /data/app/io.ionic.starter-1
06-11 12:30:49.901 467-487/? I/ActivityManager: Force stopping io.ionic.starter appid=10217 user=-1: uninstall pkg
06-11 12:30:50.007 467-498/? I/PackageManager: Package io.ionic.starter codePath changed from /data/app/io.ionic.starter-2 to /data/app/io.ionic.starter-1; Retaining data and using new
06-11 12:30:50.011 467-498/? I/PackageManager: Running dexopt on: /data/app/io.ionic.starter-1/base.apk pkg=io.ionic.starter isa=arm vmSafeMode=false
06-11 12:30:50.111 10420-10420/? I/dex2oat: /system/bin/dex2oat --zip-fd=6 --zip-location=/data/app/io.ionic.starter-1/base.apk --oat-fd=7 --oat-location=/data/dalvik-cache/arm/data@app@io.ionic.starter-1@base.apk@classes.dex --instruction-set=arm --instruction-set-features=default --runtime-arg -Xms64m --runtime-arg -Xmx512m --swap-fd=8
06-11 12:30:50.371 467-487/? I/ActivityManager: Force stopping io.ionic.starter appid=10217 user=-1: update pkg
06-11 12:30:50.372 467-498/? W/PackageManager: Code path for pkg : io.ionic.starter changing from /data/app/io.ionic.starter-2 to /data/app/io.ionic.starter-1
06-11 12:30:50.372 467-498/? W/PackageManager: Resource path for pkg : io.ionic.starter changing from /data/app/io.ionic.starter-2 to /data/app/io.ionic.starter-1
06-11 12:30:50.562 467-498/? I/ActivityManager: Force stopping io.ionic.starter appid=10217 user=0: pkg removed
06-11 12:30:50.626 467-498/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:io.ionic.starter flg=0x4000010 (has extras) }: user 12 is stopped
06-11 12:30:50.627 467-498/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.ionic.starter flg=0x4000010 (has extras) }: user 12 is stopped
06-11 12:30:50.628 467-498/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:io.ionic.starter flg=0x4000010 (has extras) }: user 12 is stopped
06-11 12:30:50.628 467-498/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.MY_PACKAGE_REPLACED flg=0x4000010 pkg=io.ionic.starter (has extras) }: user 12 is stopped
06-11 12:30:51.030 467-467/? D/BackupManagerService: Received broadcast Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:io.ionic.starter flg=0x4000010 (has extras) }
06-11 12:30:53.986 467-467/? D/BackupManagerService: Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.ionic.starter flg=0x4000010 (has extras) }
06-11 12:30:53.988 467-467/? W/BackupManagerService: Removing schedule queue dupe of io.ionic.starter
06-11 12:30:54.463 1003-1138/? W/PackageManager: Failure retrieving resources for io.ionic.starter: Resource ID #0x0
06-11 12:30:54.685 467-2129/? I/ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=io.ionic.starter/.MainActivity} from uid 2000 on display 0
06-11 12:30:54.689 467-2129/? V/WindowManager: addAppToken: AppWindowToken{38fd88b3 token=Token{2855e622 ActivityRecord{2b2ea7ed u0 io.ionic.starter/.MainActivity t947}}} to stack=1 task=947 at 0
06-11 12:30:54.697 467-492/? V/WindowManager: Adding window Window{3d02177a u0 Starting io.ionic.starter} at 3 of 9 (after Window{86faad0 u0 com.google.android.googlequicksearchbox/com.google.android.launcher.GEL})
06-11 12:30:54.907 467-830/? I/ActivityManager: Start proc 10525:io.ionic.starter/u0a217 for activity io.ionic.starter/.MainActivity
06-11 12:30:55.223 10525-10525/io.ionic.starter I/WebViewFactory: Loading com.google.android.webview version 39 (1836172-arm) (code 324901)
06-11 12:30:55.237 10525-10525/io.ionic.starter I/LibraryLoader: Time to load native libraries: 4 ms (timestamps 9078-9082)
06-11 12:30:55.237 10525-10525/io.ionic.starter I/LibraryLoader: Expected native library version number "",actual native library version number ""
06-11 12:30:55.271 10525-10525/io.ionic.starter V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {2a169684}
06-11 12:30:55.272 10525-10525/io.ionic.starter I/LibraryLoader: Expected native library version number "",actual native library version number ""
06-11 12:30:55.272 10525-10525/io.ionic.starter I/chromium: [INFO:library_loader_hooks.cc(104)] Chromium logging enabled: level = 0, default verbosity = 0
06-11 12:30:55.292 10525-10525/io.ionic.starter I/BrowserStartupController: Initializing chromium process, singleProcess=true
06-11 12:30:55.293 10525-10525/io.ionic.starter W/art: Attempt to remove local handle scope entry from IRT, ignoring
06-11 12:30:55.322 10525-10552/io.ionic.starter W/AudioManagerAndroid: Requires BLUETOOTH permission
06-11 12:30:55.322 10525-10525/io.ionic.starter W/chromium: [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
06-11 12:30:55.323 10525-10525/io.ionic.starter I/chromium: [INFO:aw_browser_main_parts.cc(65)] Load from apk succesful, fd=31 off=46872 len=3037
06-11 12:30:55.456 10525-10525/io.ionic.starter I/chromium: [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:32 off:230172 len:1089587
06-11 12:30:55.552 10525-10525/io.ionic.starter D/libEGL: loaded /system/lib/egl/libEGL_tegra.so
06-11 12:30:55.608 10525-10525/io.ionic.starter D/libEGL: loaded /system/lib/egl/libGLESv1_CM_tegra.so
06-11 12:30:55.746 10525-10525/io.ionic.starter D/libEGL: loaded /system/lib/egl/libGLESv2_tegra.so
06-11 12:30:55.774 10883-10569/? D/PkgBroadcastIntentOp: Received broadcast action=android.intent.action.PACKAGE_REMOVED and uri=io.ionic.starter
06-11 12:30:55.790 10883-11198/? E/Drive.UninstallOperation: Package still installed io.ionic.starter
06-11 12:30:55.941 10525-10525/io.ionic.starter W/chromium: [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
06-11 12:30:55.957 10883-10569/? D/WearableController: Received broadcast action=android.intent.action.PACKAGE_REMOVED and uri=io.ionic.starter
06-11 12:30:56.005 10525-10525/io.ionic.starter W/art: Attempt to remove local handle scope entry from IRT, ignoring
06-11 12:30:56.010 10525-10525/io.ionic.starter W/AwContents: onDetachedFromWindow called when already detached. Ignoring
06-11 12:30:56.026 10883-10574/? D/gH_MetricsDatabase: 0 metrics were deleted when clearing package io.ionic.starter.
06-11 12:30:56.031 10525-10525/io.ionic.starter D/SystemWebViewEngine: CordovaWebView is running on device made by: asus
06-11 12:30:56.039 10525-10525/io.ionic.starter W/art: Attempt to remove local handle scope entry from IRT, ignoring
06-11 12:30:56.039 10525-10525/io.ionic.starter W/art: Attempt to remove local handle scope entry from IRT, ignoring
06-11 12:30:56.140 10525-10611/io.ionic.starter D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
06-11 12:30:56.145 22935-10610/? I/UpdateIcingCorporaServi: Updating corpora: APPS=io.ionic.starter, CONTACTS=MAYBE
06-11 12:30:56.147 10525-10525/io.ionic.starter D/Atlas: Validating map...
06-11 12:30:56.150 10883-10569/? D/PkgBroadcastIntentOp: Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=io.ionic.starter
06-11 12:30:56.165 467-2048/? V/WindowManager: Adding window Window{3ace9083 u0 io.ionic.starter/io.ionic.starter.MainActivity} at 3 of 10 (before Window{3d02177a u0 Starting io.ionic.starter})
06-11 12:30:56.190 10883-11198/? D/osz: Processing package: io.ionic.starter
06-11 12:30:56.194 10883-10569/? D/WearableController: Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=io.ionic.starter
06-11 12:30:56.214 467-2121/? V/WindowManager: Adding window Window{3fb78cfb u0 io.ionic.starter/io.ionic.starter.MainActivity} at 4 of 11 (before Window{3d02177a u0 Starting io.ionic.starter})
06-11 12:30:56.219 10525-10525/io.ionic.starter V/StatusBar: StatusBar: initialization
06-11 12:30:56.251 467-2048/? V/WindowManager: Adding window Window{dc9e771 u0 io.ionic.starter/io.ionic.starter.MainActivity} at 3 of 12 (before Window{3ace9083 u0 io.ionic.starter/io.ionic.starter.MainActivity})
06-11 12:30:56.254 10883-11198/? D/GassUtils: Found app info for package io.ionic.starter:18. Hash: 59c03aa5c053481d7c902c53f2e3a55b9aa45dc51a6e4a37500f6f21a393a83b
06-11 12:30:56.255 10883-11198/? D/osz: Found info for package io.ionic.starter in db.
06-11 12:30:56.281 10525-10611/io.ionic.starter I/OpenGLRenderer: Initialized EGL, version 1.4
06-11 12:30:56.286 10525-10611/io.ionic.starter D/OpenGLRenderer: Enabling debug mode 0
06-11 12:30:56.385 8000-8000/? I/Finsky: [1] com.google.android.finsky.utils.bh.run(2302): Package state data is missing for io.ionic.starter
06-11 12:30:56.487 467-617/? I/WindowManager: Switching to real app window: Window{dc9e771 u0 io.ionic.starter/io.ionic.starter.MainActivity}
06-11 12:30:56.581 467-492/? I/ActivityManager: Displayed io.ionic.starter/.MainActivity: +1s712ms
06-11 12:30:57.436 10883-10569/? D/PkgBroadcastIntentOp: Received broadcast action=android.intent.action.PACKAGE_REPLACED and uri=io.ionic.starter
06-11 12:30:57.494 10883-11259/? D/osz: Processing package: io.ionic.starter
06-11 12:30:57.513 10883-11259/? D/GassUtils: Found app info for package io.ionic.starter:18. Hash: 59c03aa5c053481d7c902c53f2e3a55b9aa45dc51a6e4a37500f6f21a393a83b
06-11 12:30:57.513 10883-11259/? D/osz: Found info for package io.ionic.starter in db.
06-11 12:30:59.526 10525-10525/io.ionic.starter I/chromium: [INFO:CONSOLE(32395)] "Uncaught TypeError: undefined is not a function", source: file:///android_asset/www/build/js/app.bundle.js (32395)
```

**Comment by gdesio75** [comment] 2016-06-24 20:16
Same issue for me also running in browser:

`Failed to load resource: the server responded with a status of 404 (Not Found)    http://127.0.0.1:8100/build/js/app.bundle.js`

**Comment by brandyscarney** [comment] 2016-06-24 21:08
Can you please run `ionic info` inside of the project and paste the output here? Also run the following and paste the output:

```
npm -v
node -v
```

Thanks!

**Comment by gdesio75** [comment] 2016-06-25 11:33
The output you requested:

```
$ ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.3.1 Build version 7D1014 

$ npm -v
2.14.7

$ node -v
v4.2.2
```

Thnx.

**Comment by 1415003719** [comment] 2016-07-05 11:34
slides not work in android

**Comment by brandyscarney** [comment] 2016-07-22 17:18
@ehussain @gdesio75 Are you still having this issue with the latest code? The typescript errors have been fixed. If you could give me some more information about the android device you're using that would be great. :) 

Make sure to run `npm install` after pulling the latest code to test. Thanks!

**Comment by brandyscarney** [comment] 2016-08-08 21:34
I haven't been able to reproduce this issue and since it's been awhile since anyone has replied I am going to close it. Please let me know if you're still running into it though and I will reopen it. Thanks!

**Closed by brandyscarney** 2016-08-08 21:34 UTC
