### ISSUE TITLE
Ionic popover is not getting styling first time.

### ISSUE THREAD

**Issue by umasoodch** [driftyco/ionic-preview-app#77] opened 2016-12-28 11:57 UTC
After loading a app first time there are some default classes on ionic popover. These are two divs including popover-arrow and popover-content and both divs have no styling at first time. But after reloading the whole application then I can see the classes on these two divs. 

Any help would be highly appreciated.

**Comment by brandyscarney** [comment] 2017-01-03 15:46
Could you give me some more information please? Is this issue pertaining to the preview app's popover demo or your personal app? 

If this is happening on the preview app: which environment are you running it on? a browser? iOS device? emulator?

If this is happening on your personal app: please create an issue on the Ionic repo with a plunker, github repository or steps to reproduce: https://github.com/driftyco/ionic

Thanks!

**Comment by brandyscarney** [comment] 2017-01-23 16:27
I'm going to close this since it's been awhile since there was a reply and we have made a lot of changes to popover since. Thanks!

**Closed by brandyscarney** 2017-01-23 16:27 UTC
Labels: needs reply
