### ISSUE TITLE
when i set dismissOnPageChange: true  it will error:error_handler.js:47 EXCEPTION: Uncaught (in promise): false

### ISSUE THREAD

**Issue by hmxcn33** [driftyco/ionic-preview-app#75] opened 2016-12-20 06:24 UTC
error_handler.js:47 EXCEPTION: Uncaught (in promise): false

ErrorHandler.handleError @ error_handler.js:47
IonicErrorHandler.handleError @ ionic-error-handler.js:56
next @ application_ref.js:272
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
NgZone.triggerError @ ng_zone.js:278
onHandleError @ ng_zone.js:257
t.handleError @ polyfills.js:3
e.runGuarded @ polyfills.js:3
r @ polyfills.js:3
i @ polyfills.js:3
invoke @ polyfills.js:3

**Comment by brandyscarney** [comment] 2016-12-20 15:39
Thanks for the issue! Since this is a problem with Ionic itself I am going to close it as a duplicate of https://github.com/driftyco/ionic/issues/9589. We are actively investigating the issue.

**Closed by brandyscarney** 2016-12-20 15:39 UTC
