### ISSUE TITLE
On click fab button it doesn't showing the list in emulator 

### ISSUE THREAD

**Issue by umesh190690** [driftyco/ionic-preview-app#102] opened 2017-04-27 10:40 UTC
when i click on fab button(Share) it does not show the  fab-list (facebook,twitter)but it showing in web brower but not in ios emulator

```
 <ion-fab  right bottom #fab>
   <button ion-fab>Share</button>
   <ion-fab-list side="top">
     <button ion-fab (click)="share('facebook', fab)">Facebook</button>
     <button ion-fab (click)="share('twitter', fab)">Twitter</button>
   </ion-fab-list>
 </ion-fab>
```

**Comment by brandyscarney** [comment] 2017-05-09 21:59
I'm not able to reproduce this. If you're still having this issue, which emulator are you using?

**Comment by brandyscarney** [comment] 2017-05-11 18:09
I'm going to close this since I can't reproduce it and I don't think it is an issue with the preview app. If you're still running into this issue can you please open an issue on the [ionic repository](https://github.com/driftyco/ionic/issues) and fill out the issue template with how we can reproduce it. Thanks!

**Closed by brandyscarney** 2017-05-11 18:09 UTC
Labels: needs reply
